
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Article extends ContentItem {
    public author!: Elements.LinkedItemsElement<ContentItem>;
    public displayOptions!: Elements.MultipleChoiceElement;
    public nextSteps!: Elements.RichTextElement;
    public contentInsights!: Elements.CustomElement;
    public content!: Elements.RichTextElement;
    public url!: Elements.UrlSlugElement;
    public platform!: Elements.TaxonomyElement;
    public displayMode!: Elements.MultipleChoiceElement;
    public shortTitle!: Elements.TextElement;
    public visibility!: Elements.TaxonomyElement;
    public title!: Elements.TextElement;
    public redirectUrls!: Elements.TextElement;
    public introduction!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'display_options') {
                    return 'displayOptions';
                }
                if (elementName === 'next_steps') {
                    return 'nextSteps';
                }
                if (elementName === 'content_insights') {
                    return 'contentInsights';
                }
                if (elementName === 'display_mode') {
                    return 'displayMode';
                }
                if (elementName === 'short_title') {
                    return 'shortTitle';
                }
                if (elementName === 'redirect_urls') {
                    return 'redirectUrls';
                }
                return elementName;
            })
        });
    }
}
