var KenticoCloud = require('kentico-cloud-delivery');

/**
* This class was generated by 'kentico-cloud-model-generator-utility' at Thu Feb 21 2019 07:30:08 GMT+0100 (GMT+01:00).
*/
class Article extends KenticoCloud.ContentItem {
    constructor() {
        super({
            propertyResolver: ((fieldName) => {
                if (fieldName === 'next_steps') {
                    return 'nextSteps';
                }
                if (fieldName === 'short_title') {
                    return 'shortTitle';
                }
                if (fieldName === 'content_type') {
                    return 'contentType';
                }
                if (fieldName === 'vanity_urls') {
                    return 'vanityUrls';
                }
                if (fieldName === 'visibility_baa84fa') {
                    return 'visibilityBaa84fa';
                }
                return fieldName;
            })
        });
    }
}

module.exports = Article;
