const KenticoCloud = require('kentico-cloud-delivery');

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Fri Feb 22 2019 13:15:49 GMT+0100 (Central Europe Standard Time).
 */
class Article extends KenticoCloud.ContentItem {
    constructor() {
        super({
            propertyResolver: ((fieldName) => {
                if (fieldName === 'next_steps') {
                    return 'nextSteps';
                }
                if (fieldName === 'content_type') {
                    return 'contentType';
                }
                if (fieldName === 'short_title') {
                    return 'shortTitle';
                }
                if (fieldName === 'vanity_urls') {
                    return 'vanityUrls';
                }
                if (fieldName === 'programming_language') {
                    return 'programmingLanguage';
                }
                return fieldName;
            }),
        });
    }
}

module.exports = Article;
