const KenticoCloud = require('kentico-cloud-delivery');

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Thu Mar 07 2019 13:47:20 GMT+0100 (GMT+01:00).
 */
class CodeSample extends KenticoCloud.ContentItem {
    constructor() {
        super({
            propertyResolver: ((fieldName) => {
                if (fieldName === 'programming_language') {
                    return 'programmingLanguage';
                }
                return fieldName;
            })
        });
    }
}

module.exports = CodeSample;
