
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class CodeSample extends ContentItem {
    public code!: Elements.TextElement;
    public programmingLanguage!: Elements.TaxonomyElement;
    public platform!: Elements.TaxonomyElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'programming_language') {
                    return 'programmingLanguage';
                }
                return elementName;
            })
        });
    }
}
