
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class EmailNotification extends ContentItem {
    public subject!: Elements.TextElement;
    public senderName!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'sender_name') {
                    return 'senderName';
                }
                return elementName;
            })
        });
    }
}
