
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Footer extends ContentItem {
    public copyright!: Elements.RichTextElement;
    public externalLinks!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'external_links') {
                    return 'externalLinks';
                }
                return elementName;
            })
        });
    }
}
