
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ReleaseNote extends ContentItem {
    public affectedServices!: Elements.MultipleChoiceElement;
    public releaseDate!: Elements.DateTimeElement;
    public content!: Elements.RichTextElement;
    public severity!: Elements.MultipleChoiceElement;
    public title!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'affected_services') {
                    return 'affectedServices';
                }
                if (elementName === 'release_date') {
                    return 'releaseDate';
                }
                return elementName;
            })
        });
    }
}
