
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Scenario extends ContentItem {
    public title!: Elements.TextElement;
    public shortTitle!: Elements.TextElement;
    public introduction!: Elements.RichTextElement;
    public content!: Elements.RichTextElement;
    public children!: Elements.LinkedItemsElement<ContentItem>;
    public author!: Elements.LinkedItemsElement<ContentItem>;
    public visibility!: Elements.TaxonomyElement;
    public url!: Elements.UrlSlugElement;
    public redirectUrls!: Elements.TextElement;
    public notes!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'short_title') {
                    return 'shortTitle';
                }
                if (elementName === 'redirect_urls') {
                    return 'redirectUrls';
                }
                return elementName;
            })
        });
    }
}
