const KenticoCloud = require('@kentico/kontent-delivery');

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Thu Feb 21 2019 06:42:15 GMT+0100 (GMT+01:00).
 */
class Scenario extends KenticoCloud.ContentItem {
    constructor() {
        super({
            propertyResolver: ((fieldName) => {
                if (fieldName === 'short_title') {
                    return 'shortTitle';
                }
                if (fieldName === 'intended_audience') {
                    return 'intendedAudience';
                }
                if (fieldName === 'vanity_urls') {
                    return 'vanityUrls';
                }
                return fieldName;
            }),
        });
    }
}

module.exports = Scenario;
