
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Signpost extends ContentItem {
    public title!: Elements.TextElement;
    public description!: Elements.RichTextElement;
    public content!: Elements.RichTextElement;
    public itemsToShow!: Elements.NumberElement;
    public type!: Elements.MultipleChoiceElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'items_to_show') {
                    return 'itemsToShow';
                }
                return elementName;
            })
        });
    }
}
