
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingPage extends ContentItem {
    public title!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public description!: Elements.RichTextElement;
    public duration!: Elements.TextElement;
    public callToAction!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public course!: Elements.TaxonomyElement;
    public url!: Elements.UrlSlugElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'call_to_action') {
                    return 'callToAction';
                }
                return elementName;
            })
        });
    }
}
