
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingCourse extends ContentItem {
    public redirectUrls!: Elements.TextElement;
    public persona!: Elements.MultipleChoiceElement;
    public title!: Elements.TextElement;
    public talentlmsCourseIdPreview!: Elements.NumberElement;
    public displayOptions!: Elements.MultipleChoiceElement;
    public trainingCourse!: Elements.TaxonomyElement;
    public url!: Elements.UrlSlugElement;
    public talentlmsCourseId!: Elements.NumberElement;
    public introduction!: Elements.RichTextElement;
    public thumbnail!: Elements.AssetsElement;
    public duration!: Elements.NumberElement;
    public description!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'redirect_urls') {
                    return 'redirectUrls';
                }
                if (elementName === 'talentlms_course_id_preview') {
                    return 'talentlmsCourseIdPreview';
                }
                if (elementName === 'display_options') {
                    return 'displayOptions';
                }
                if (elementName === 'training_course') {
                    return 'trainingCourse';
                }
                if (elementName === 'talentlms_course_id') {
                    return 'talentlmsCourseId';
                }
                return elementName;
            })
        });
    }
}
