
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingVideoSubtitle extends ContentItem {
    public subtitleFile!: Elements.AssetsElement;
    public subtitleLanguage!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'subtitle_file') {
                    return 'subtitleFile';
                }
                if (elementName === 'subtitle_language') {
                    return 'subtitleLanguage';
                }
                return elementName;
            })
        });
    }
}
