
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingNarrative extends ContentItem {
    public narrativeItems!: Elements.RichTextElement;
    public adaptComponentTitleTitle!: Elements.TextElement;
    public adaptComponentInstructionInstruction!: Elements.RichTextElement;
    public description!: Elements.RichTextElement;
    public forceCompletion!: Elements.MultipleChoiceElement;
    public adaptProgressSettingsAdjustProgressSettings!: Elements.MultipleChoiceElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'narrative_items') {
                    return 'narrativeItems';
                }
                if (elementName === 'adapt_component_title__title') {
                    return 'adaptComponentTitleTitle';
                }
                if (elementName === 'adapt_component_instruction__instruction') {
                    return 'adaptComponentInstructionInstruction';
                }
                if (elementName === 'force_completion_') {
                    return 'forceCompletion';
                }
                if (elementName === 'adapt_progress_settings__adjust_progress_settings') {
                    return 'adaptProgressSettingsAdjustProgressSettings';
                }
                return elementName;
            })
        });
    }
}
