
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingCertificationTest extends ContentItem {
    public headingForIncorrectAnswers!: Elements.RichTextElement;
    public introduction!: Elements.RichTextElement;
    public url!: Elements.UrlSlugElement;
    public questionGroups!: Elements.LinkedItemsElement<ContentItem>;
    public failureMessage!: Elements.RichTextElement;
    public certificateValidity!: Elements.NumberElement;
    public successMessage!: Elements.RichTextElement;
    public testDuration!: Elements.NumberElement;
    public scoreToPass!: Elements.NumberElement;
    public personasTopicsTrainingPersona!: Elements.TaxonomyElement;
    public personasTopicsTrainingTopic!: Elements.TaxonomyElement;
    public title!: Elements.TextElement;
    public description!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'heading_for_incorrect_answers') {
                    return 'headingForIncorrectAnswers';
                }
                if (elementName === 'question_groups') {
                    return 'questionGroups';
                }
                if (elementName === 'failure_message') {
                    return 'failureMessage';
                }
                if (elementName === 'certificate_validity') {
                    return 'certificateValidity';
                }
                if (elementName === 'success_message') {
                    return 'successMessage';
                }
                if (elementName === 'test_duration') {
                    return 'testDuration';
                }
                if (elementName === 'score_to_pass') {
                    return 'scoreToPass';
                }
                if (elementName === 'personas___topics__training_persona') {
                    return 'personasTopicsTrainingPersona';
                }
                if (elementName === 'personas___topics__training_topic') {
                    return 'personasTopicsTrainingTopic';
                }
                return elementName;
            })
        });
    }
}
