
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingSurvey extends ContentItem {
    public title!: Elements.TextElement;
    public uiMessageAndCta!: Elements.RichTextElement;
    public url!: Elements.UrlSlugElement;
    public shortIntroduction!: Elements.TextElement;
    public surveyQuestions!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'ui_message_and_cta') {
                    return 'uiMessageAndCta';
                }
                if (elementName === 'short_introduction') {
                    return 'shortIntroduction';
                }
                if (elementName === 'survey_questions') {
                    return 'surveyQuestions';
                }
                return elementName;
            })
        });
    }
}
