
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingAnswer extends ContentItem {
    public incorrectFeedback!: Elements.RichTextElement;
    public answer!: Elements.RichTextElement;
    public correctAnswer!: Elements.MultipleChoiceElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'incorrect_feedback') {
                    return 'incorrectFeedback';
                }
                if (elementName === 'correct_answer') {
                    return 'correctAnswer';
                }
                return elementName;
            })
        });
    }
}
