
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingQuestionForSurveyAndTest extends ContentItem {
    public sourceDetailsNotes!: Elements.RichTextElement;
    public answers!: Elements.RichTextElement;
    public question!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'source__details__notes') {
                    return 'sourceDetailsNotes';
                }
                return elementName;
            })
        });
    }
}
