
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingAnswerForSurveyAndTest extends ContentItem {
    public answer!: Elements.RichTextElement;
    public isThisACorrectAnswer!: Elements.MultipleChoiceElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'is_this_a_correct_answer_') {
                    return 'isThisACorrectAnswer';
                }
                return elementName;
            })
        });
    }
}
