
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingHotGraphicPin extends ContentItem {
    public body!: Elements.TextElement;
    public left!: Elements.NumberElement;
    public top!: Elements.NumberElement;
    public title!: Elements.TextElement;
    public image!: Elements.AssetsElement;
}
