
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingDragAndDrop extends ContentItem {
    public incorrectAnswerFeedback!: Elements.RichTextElement;
    public adaptComponentTitleTitle!: Elements.TextElement;
    public correctAnswerFeedback!: Elements.RichTextElement;
    public dropAreas!: Elements.RichTextElement;
    public partlyCorrectAnswerFeedback!: Elements.RichTextElement;
    public content!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'incorrect_answer_feedback') {
                    return 'incorrectAnswerFeedback';
                }
                if (elementName === 'adapt_component_title__title') {
                    return 'adaptComponentTitleTitle';
                }
                if (elementName === 'correct_answer_feedback') {
                    return 'correctAnswerFeedback';
                }
                if (elementName === 'drop_areas') {
                    return 'dropAreas';
                }
                if (elementName === 'partly_correct_answer_feedback') {
                    return 'partlyCorrectAnswerFeedback';
                }
                return elementName;
            })
        });
    }
}
