
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingSubscriptions extends ContentItem {
    public subscriptionServicePackageCodeName!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'subscription_service_package_code_name') {
                    return 'subscriptionServicePackageCodeName';
                }
                return elementName;
            })
        });
    }
}
