
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingBlock extends ContentItem {
    public adaptProgressSettingsAdjustProgressSettings!: Elements.MultipleChoiceElement;
    public title!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public body!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'adapt_progress_settings__adjust_progress_settings') {
                    return 'adaptProgressSettingsAdjustProgressSettings';
                }
                return elementName;
            })
        });
    }
}
