
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingVideo extends ContentItem {
    public adaptComponentTitleTitle!: Elements.TextElement;
    public adaptComponentInstructionInstruction!: Elements.RichTextElement;
    public forceCompletion!: Elements.MultipleChoiceElement;
    public adaptProgressSettingsAdjustProgressSettings!: Elements.MultipleChoiceElement;
    public description!: Elements.RichTextElement;
    public descriptionOld!: Elements.TextElement;
    public loadingImage!: Elements.AssetsElement;
    public displayoptionsCssClasses!: Elements.TaxonomyElement;
    public subtitles!: Elements.RichTextElement;
    public transcript!: Elements.RichTextElement;
    public displayoptionsLayout!: Elements.MultipleChoiceElement;
    public videoFile!: Elements.AssetsElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'adapt_component_title__title') {
                    return 'adaptComponentTitleTitle';
                }
                if (elementName === 'adapt_component_instruction__instruction') {
                    return 'adaptComponentInstructionInstruction';
                }
                if (elementName === 'force_completion_') {
                    return 'forceCompletion';
                }
                if (elementName === 'adapt_progress_settings__adjust_progress_settings') {
                    return 'adaptProgressSettingsAdjustProgressSettings';
                }
                if (elementName === 'description_old') {
                    return 'descriptionOld';
                }
                if (elementName === 'loading_image') {
                    return 'loadingImage';
                }
                if (elementName === 'displayoptions__css_classes') {
                    return 'displayoptionsCssClasses';
                }
                if (elementName === 'displayoptions__layout') {
                    return 'displayoptionsLayout';
                }
                if (elementName === 'video_file') {
                    return 'videoFile';
                }
                return elementName;
            })
        });
    }
}
