
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TrainingQuestion extends ContentItem {
    public adaptComponentTitleTitle!: Elements.TextElement;
    public adaptComponentInstructionInstruction!: Elements.RichTextElement;
    public adaptProgressSettingsAdjustProgressSettings!: Elements.MultipleChoiceElement;
    public feedbackTitle!: Elements.TextElement;
    public question!: Elements.RichTextElement;
    public feedbackIfCorrect!: Elements.RichTextElement;
    public displayoptionsCssClasses!: Elements.TaxonomyElement;
    public answers!: Elements.RichTextElement;
    public feedbackIfPartlyCorrect!: Elements.RichTextElement;
    public feedbackIfIncorrect!: Elements.RichTextElement;
    public displayoptionsLayout!: Elements.MultipleChoiceElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'adapt_component_title__title') {
                    return 'adaptComponentTitleTitle';
                }
                if (elementName === 'adapt_component_instruction__instruction') {
                    return 'adaptComponentInstructionInstruction';
                }
                if (elementName === 'adapt_progress_settings__adjust_progress_settings') {
                    return 'adaptProgressSettingsAdjustProgressSettings';
                }
                if (elementName === 'feedback_title') {
                    return 'feedbackTitle';
                }
                if (elementName === 'feedback_if_correct') {
                    return 'feedbackIfCorrect';
                }
                if (elementName === 'displayoptions__css_classes') {
                    return 'displayoptionsCssClasses';
                }
                if (elementName === 'feedback_if_partly_correct') {
                    return 'feedbackIfPartlyCorrect';
                }
                if (elementName === 'feedback_if_incorrect') {
                    return 'feedbackIfIncorrect';
                }
                if (elementName === 'displayoptions__layout') {
                    return 'displayoptionsLayout';
                }
                return elementName;
            })
        });
    }
}
