
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class UiMessages extends ContentItem {
    public videoReplay!: Elements.TextElement;
    public searchPlaceholder!: Elements.TextElement;
    public feedbackFormYesButton!: Elements.TextElement;
    public formFieldValidationEmptyField!: Elements.TextElement;
    public trainingCtaRevisitCourse!: Elements.TextElement;
    public bannerForDevEnvironment!: Elements.RichTextElement;
    public bannerForPreviewEnvironment!: Elements.RichTextElement;
    public codeBlockCopyCodeButtonActive!: Elements.TextElement;
    public signInErrorText!: Elements.RichTextElement;
    public trainingSignIn!: Elements.TextElement;
    public nextPartLinkText!: Elements.TextElement;
    public trainingAddToLinkedin!: Elements.TextElement;
    public trainingEstimatedDuration!: Elements.TextElement;
    public articleNoAuthor!: Elements.TextElement;
    public trainingCtaBuyCourse!: Elements.TextElement;
    public cookiePolicyBar!: Elements.RichTextElement;
    public trainingCtaBuyLink!: Elements.TextElement;
    public feedbackFormNoButton!: Elements.TextElement;
    public linkToAppTooltip!: Elements.TextElement;
    public signInButton!: Elements.TextElement;
    public technologyPickerTooltip!: Elements.TextElement;
    public portalName!: Elements.TextElement;
    public toggleBreakingChangesOnly!: Elements.TextElement;
    public articleNextSteps!: Elements.TextElement;
    public videoExpand!: Elements.TextElement;
    public signOutButton!: Elements.TextElement;
    public feedbackFormFeedbackLabel!: Elements.TextElement;
    public searchNoResults!: Elements.TextElement;
    public search404PageResults!: Elements.TextElement;
    public trainingCtaResumeCourse!: Elements.TextElement;
    public feedbackFormSubmitButton!: Elements.TextElement;
    public codeBlockCopyCodeButton!: Elements.TextElement;
    public headingCopyUrlActive!: Elements.TextElement;
    public homeShowLess!: Elements.TextElement;
    public affectedServicesSelectorTitle!: Elements.TextElement;
    public embeddedContentDntNotice!: Elements.RichTextElement;
    public codeBlockEmptyStateText!: Elements.TextElement;
    public trainingPersonasSelectorTitle!: Elements.TextElement;
    public previousPartLinkText!: Elements.TextElement;
    public feedbackFormYesMessage!: Elements.TextElement;
    public homeShowMore!: Elements.TextElement;
    public trainingDownloadCertificate!: Elements.TextElement;
    public signInErrorSubscriptionMissingText!: Elements.RichTextElement;
    public trainingCtaStartCourse!: Elements.TextElement;
    public technologySelectorLabel!: Elements.TextElement;
    public feedbackFormNoMessage!: Elements.TextElement;
    public videoPause!: Elements.TextElement;
    public feedbackFormHeading!: Elements.TextElement;
    public headingCopyUrlHover!: Elements.TextElement;
    public feedbackFormEmailLabel!: Elements.TextElement;
    public videoPlay!: Elements.TextElement;
    public formFieldValidationRecaptchaMessage!: Elements.TextElement;
    public articleIntroduction!: Elements.TextElement;
    public trainingCtaComingSoon!: Elements.TextElement;
    public trainingViewDetails!: Elements.TextElement;
    public toggleAllChanges!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'video___replay') {
                    return 'videoReplay';
                }
                if (elementName === 'search___placeholder') {
                    return 'searchPlaceholder';
                }
                if (elementName === 'feedback_form___yes_button') {
                    return 'feedbackFormYesButton';
                }
                if (elementName === 'form_field_validation___empty_field') {
                    return 'formFieldValidationEmptyField';
                }
                if (elementName === 'training___cta_revisit_course') {
                    return 'trainingCtaRevisitCourse';
                }
                if (elementName === 'banner_for_dev_environment') {
                    return 'bannerForDevEnvironment';
                }
                if (elementName === 'banner_for_preview_environment') {
                    return 'bannerForPreviewEnvironment';
                }
                if (elementName === 'code_block___copy_code_button_active') {
                    return 'codeBlockCopyCodeButtonActive';
                }
                if (elementName === 'sign_in_error_text') {
                    return 'signInErrorText';
                }
                if (elementName === 'training___sign_in') {
                    return 'trainingSignIn';
                }
                if (elementName === 'next_part_link_text') {
                    return 'nextPartLinkText';
                }
                if (elementName === 'training___add_to_linkedin') {
                    return 'trainingAddToLinkedin';
                }
                if (elementName === 'training___estimated_duration') {
                    return 'trainingEstimatedDuration';
                }
                if (elementName === 'article___no_author') {
                    return 'articleNoAuthor';
                }
                if (elementName === 'training___cta_buy_course') {
                    return 'trainingCtaBuyCourse';
                }
                if (elementName === 'cookie_policy_bar') {
                    return 'cookiePolicyBar';
                }
                if (elementName === 'training___cta_buy_link') {
                    return 'trainingCtaBuyLink';
                }
                if (elementName === 'feedback_form___no_button') {
                    return 'feedbackFormNoButton';
                }
                if (elementName === 'link_to_app_tooltip') {
                    return 'linkToAppTooltip';
                }
                if (elementName === 'sign_in_button') {
                    return 'signInButton';
                }
                if (elementName === 'technology_picker_tooltip') {
                    return 'technologyPickerTooltip';
                }
                if (elementName === 'portal_name') {
                    return 'portalName';
                }
                if (elementName === 'toggle_breaking_changes_only') {
                    return 'toggleBreakingChangesOnly';
                }
                if (elementName === 'article___next_steps') {
                    return 'articleNextSteps';
                }
                if (elementName === 'video___expand') {
                    return 'videoExpand';
                }
                if (elementName === 'sign_out_button') {
                    return 'signOutButton';
                }
                if (elementName === 'feedback_form___feedback_label') {
                    return 'feedbackFormFeedbackLabel';
                }
                if (elementName === 'search___no_results') {
                    return 'searchNoResults';
                }
                if (elementName === 'search___404_page_results') {
                    return 'search404PageResults';
                }
                if (elementName === 'training___cta_resume_course') {
                    return 'trainingCtaResumeCourse';
                }
                if (elementName === 'feedback_form___submit_button') {
                    return 'feedbackFormSubmitButton';
                }
                if (elementName === 'code_block___copy_code_button') {
                    return 'codeBlockCopyCodeButton';
                }
                if (elementName === 'heading___copy_url_active') {
                    return 'headingCopyUrlActive';
                }
                if (elementName === 'home___show_less') {
                    return 'homeShowLess';
                }
                if (elementName === 'affected_services_selector_title') {
                    return 'affectedServicesSelectorTitle';
                }
                if (elementName === 'embedded_content_dnt_notice') {
                    return 'embeddedContentDntNotice';
                }
                if (elementName === 'code_block___empty_state_text') {
                    return 'codeBlockEmptyStateText';
                }
                if (elementName === 'training___personas_selector_title') {
                    return 'trainingPersonasSelectorTitle';
                }
                if (elementName === 'previous_part_link_text') {
                    return 'previousPartLinkText';
                }
                if (elementName === 'feedback_form___yes_message') {
                    return 'feedbackFormYesMessage';
                }
                if (elementName === 'home___show_more') {
                    return 'homeShowMore';
                }
                if (elementName === 'training___download_certificate') {
                    return 'trainingDownloadCertificate';
                }
                if (elementName === 'sign_in_error_subscription_missing_text') {
                    return 'signInErrorSubscriptionMissingText';
                }
                if (elementName === 'training___cta_start_course') {
                    return 'trainingCtaStartCourse';
                }
                if (elementName === 'technology_selector_label') {
                    return 'technologySelectorLabel';
                }
                if (elementName === 'feedback_form___no_message') {
                    return 'feedbackFormNoMessage';
                }
                if (elementName === 'video___pause') {
                    return 'videoPause';
                }
                if (elementName === 'feedback_form___heading') {
                    return 'feedbackFormHeading';
                }
                if (elementName === 'heading___copy_url_hover') {
                    return 'headingCopyUrlHover';
                }
                if (elementName === 'feedback_form___email_label') {
                    return 'feedbackFormEmailLabel';
                }
                if (elementName === 'video___play') {
                    return 'videoPlay';
                }
                if (elementName === 'form_field_validation___recaptcha_message') {
                    return 'formFieldValidationRecaptchaMessage';
                }
                if (elementName === 'article___introduction') {
                    return 'articleIntroduction';
                }
                if (elementName === 'training___cta_coming_soon') {
                    return 'trainingCtaComingSoon';
                }
                if (elementName === 'training___view_details') {
                    return 'trainingViewDetails';
                }
                if (elementName === 'toggle_all_changes') {
                    return 'toggleAllChanges';
                }
                return elementName;
            })
        });
    }
}
