
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ZapiSchemaString extends ContentItem {
    public commonSchemaElementsName!: Elements.TextElement;
    public commonSchemaElementsDescription!: Elements.RichTextElement;
    public commonSchemaElementsExample!: Elements.TextElement;
    public defaultValue!: Elements.TextElement;
    public format!: Elements.TextElement;
    public acceptedValues!: Elements.TextElement;
    public minlength!: Elements.NumberElement;
    public maxlength!: Elements.NumberElement;
    public commonSchemaObjectPropertyElementsNullable!: Elements.MultipleChoiceElement;
    public commonSchemaObjectPropertyElementsDeprecated!: Elements.MultipleChoiceElement;
    public commonSchemaObjectPropertyElementsReadonly!: Elements.MultipleChoiceElement;
    public commonSchemaObjectPropertyElementsWriteonly!: Elements.MultipleChoiceElement;
    public apiReference!: Elements.TaxonomyElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'common_schema_elements__name') {
                    return 'commonSchemaElementsName';
                }
                if (elementName === 'common_schema_elements__description') {
                    return 'commonSchemaElementsDescription';
                }
                if (elementName === 'common_schema_elements__example') {
                    return 'commonSchemaElementsExample';
                }
                if (elementName === 'default_value') {
                    return 'defaultValue';
                }
                if (elementName === 'accepted_values') {
                    return 'acceptedValues';
                }
                if (elementName === 'common_schema_object_property_elements__nullable') {
                    return 'commonSchemaObjectPropertyElementsNullable';
                }
                if (elementName === 'common_schema_object_property_elements__deprecated') {
                    return 'commonSchemaObjectPropertyElementsDeprecated';
                }
                if (elementName === 'common_schema_object_property_elements__readonly') {
                    return 'commonSchemaObjectPropertyElementsReadonly';
                }
                if (elementName === 'common_schema_object_property_elements__writeonly') {
                    return 'commonSchemaObjectPropertyElementsWriteonly';
                }
                if (elementName === 'api_reference') {
                    return 'apiReference';
                }
                return elementName;
            })
        });
    }
}
