
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ZapiSchemaObject extends ContentItem {
    public commonSchemaElementsName!: Elements.TextElement;
    public commonSchemaElementsDescription!: Elements.RichTextElement;
    public commonSchemaElementsExample!: Elements.TextElement;
    public required!: Elements.TextElement;
    public properties!: Elements.RichTextElement;
    public additionalPropertiesName!: Elements.TextElement;
    public additionalProperties!: Elements.RichTextElement;
    public apiReference!: Elements.TaxonomyElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'common_schema_elements__name') {
                    return 'commonSchemaElementsName';
                }
                if (elementName === 'common_schema_elements__description') {
                    return 'commonSchemaElementsDescription';
                }
                if (elementName === 'common_schema_elements__example') {
                    return 'commonSchemaElementsExample';
                }
                if (elementName === 'additional_properties_name') {
                    return 'additionalPropertiesName';
                }
                if (elementName === 'additional_properties') {
                    return 'additionalProperties';
                }
                if (elementName === 'api_reference') {
                    return 'apiReference';
                }
                return elementName;
            })
        });
    }
}
