
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ZapiDiscriminatorMapItem extends ContentItem {
    public schema!: Elements.LinkedItemsElement<ContentItem>;
    public discriminatorValue!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'discriminator_value') {
                    return 'discriminatorValue';
                }
                return elementName;
            })
        });
    }
}
