
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ZapiParameter extends ContentItem {
    public name!: Elements.TextElement;
    public location!: Elements.MultipleChoiceElement;
    public description!: Elements.RichTextElement;
    public example!: Elements.TextElement;
    public schema!: Elements.LinkedItemsElement<ContentItem>;
    public required!: Elements.MultipleChoiceElement;
    public deprecated!: Elements.MultipleChoiceElement;
    public style!: Elements.MultipleChoiceElement;
    public explode!: Elements.MultipleChoiceElement;
    public apiReference!: Elements.TaxonomyElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'api_reference') {
                    return 'apiReference';
                }
                return elementName;
            })
        });
    }
}
