
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ZapiPathOperation extends ContentItem {
    public description!: Elements.RichTextElement;
    public codeSamples!: Elements.LinkedItemsElement<ContentItem>;
    public path!: Elements.TextElement;
    public requestBody!: Elements.RichTextElement;
    public apiReference!: Elements.TaxonomyElement;
    public responses!: Elements.RichTextElement;
    public pathOperation!: Elements.TaxonomyElement;
    public deprecated!: Elements.MultipleChoiceElement;
    public url!: Elements.UrlSlugElement;
    public name!: Elements.TextElement;
    public parameters!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'code_samples') {
                    return 'codeSamples';
                }
                if (elementName === 'request_body') {
                    return 'requestBody';
                }
                if (elementName === 'api_reference') {
                    return 'apiReference';
                }
                if (elementName === 'path_operation') {
                    return 'pathOperation';
                }
                return elementName;
            })
        });
    }
}
